services:
  postgres:
    image: postgres:15
    container_name: apex_postgres
    restart: always
    environment:
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apex_finance
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: apex_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: . # Look at the root folder
      dockerfile: backend/Dockerfile # Path to the file inside the folder
    container_name: apex_backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://agent_user:password@postgres:5432/apex_finance
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=your_api_key_here
      - GROQ_API_KEY=your_groq_api_key_here

  frontend:
    build: ./frontend
    container_name: apex_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: apex_worker
    command: celery -A celery_app.celery worker --loglevel=info -P eventlet --concurrency=1
    depends_on:
      - redis
      - postgres
      - backend
    environment:
      - DATABASE_URL=postgresql://agent_user:password@postgres:5432/apex_finance
      - REDIS_URL=redis://redis:6379/0
      - GROQ_API_KEY=your_groq_api_key_here

  celery_beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: apex_beat
    command: celery -A celery_app.celery beat --loglevel=info
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_URL=redis://redis:6379/0
